# Generated by Django 3.2.3 on 2021-05-22 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='company',
            new_name='name',
        ),
    ]
