# Generated by Django 3.2.3 on 2021-05-26 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20210526_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='max_client',
            new_name='max_clients',
        ),
    ]
