# Generated by Django 4.0 on 2021-12-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_plan_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='stipe_customer_id',
            new_name='stripe_customer_id',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='stipe_subscription_id',
            new_name='stripe_subscription_id',
        ),
    ]
