# Generated by Django 4.0 on 2021-12-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_rename_stipe_customer_id_team_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(default='Free', max_length=255),
        ),
    ]
